Code review request
KaushikShivam/tic-tac-toe pull request #2
Opened 2019-08-09 21:01 UTC by abdellani

2019-08-10 00:16 UTC, mosaaleb commented
#### Reviewing

2019-08-10 15:51 UTC, mosaaleb requested changes
### Amazing work @KaushikShivam, @abdellani :clap:

The logic is correct and the gameplay is nice. Yet there is still some requirements needs to be met before moving on.

- [ ] Also there is alot of ruby styling guidelines problems. Take alook at [this](https://github.com/rubocop-hq/ruby-style-guide), and let's fix these problems.

**TIP** You can install rubocop extension in your preferred code editor to catch these errors while you writing your code.

- [ ] Using [Stickler](https://github.com/microverseinc/linters-config/blob/master/ruby/) is a crucial requirement in microverse. Let's add it and make sure that we have passed all the checks.

![Screenshot from 2019-08-10 17-46-31](https://user-images.githubusercontent.com/4246637/62823893-d71cfb00-bb96-11e9-923e-25914df22d89.png)

Please handle these requirements and submit a new code review.

### Happy Coding :comptuer:

2019-08-10 15:51 UTC, mosaaleb commented on lib/game.rb
> +
**`[OPTIONAL]`** Depend on behavior not Data: Data can be accessed in one of two ways, you can refer directly to the instance variable, or wrap the variable in accessor method -- You have already accessor for `active_player`. So instead of using `@active_player` we can depend on behavior by using `active_player`.
This is an interesting [discussion](https://forum.upcase.com/t/using-instance-variables-vs-attribute-accessors/1788) on why always prefer accessor methods over instance variables.

2019-08-10 15:51 UTC, mosaaleb commented on lib/game.rb
> +  attr_accessor :active_player
**`[required]`** Game objects should be the only one that has the ability to change the active player. Using `attr_accessor` allow writing that property from outside this class. Apply this also to another properties in this class.

2019-08-10 15:51 UTC, mosaaleb commented on lib/game.rb
> +      return true
**`[REQUIRED]`** Use single responsibility for methods. Your methods should be doing only one thing. Let's take a look at `check_move` method: it checks for diagonal win, vertical win and horizontal win. It has a lot of logic and lots of conditionals.
We can refactor this method into three methods each one is responsible for only one thing.
```ruby
def check_move
  check_diagonal || check_vertical || check_horizontal
end 
```
Now we can implement each one separately.

2019-08-10 15:51 UTC, mosaaleb commented on lib/game.rb
> +      return 1
**`[REQUIRED]`** The same concept of single responsibility can be applied to `is_finished?`. Breaking down this method into two methods one to check if we reached a winning position, or we have reached a drawn position.
```ruby
def is_finished?
  check_move || game_drawn?
end
```
Now we are no longer depending on data (@counter), but rather our code depends on behavior. We can implement `game_drawn?` to also have single responsibility.

2019-08-10 15:51 UTC, mosaaleb commented on lib/game.rb
> +      switch_active_player
**`[OPTIONAL]`**: The same concept of depending on behavior in `@winner = @active_player`, as we can use the accessor methods.

2019-08-10 15:51 UTC, mosaaleb commented on lib/game.rb
> +
**`[REQUIRED]`** `update_matrix` methods is also bloated with alot of functionality. 
- It checks for if the slot is already taken -- We can make a new method to check for this `slot_taken?`.
- It switch players.
- It check for winning.

We can refactor this method to just fill the slot with the symbol. Then we can reuse the `check_move` and switching players and `slot_taken?` method in our main logic.

We can

2019-08-12 16:17 UTC, KaushikShivam commented on lib/game.rb
> +
Made changes!

2019-08-12 16:30 UTC, KaushikShivam commented on lib/game.rb
> +      switch_active_player
Done

2019-08-12 23:31 UTC, jofer86 commented
# Reviewing

2019-08-12 23:36 UTC, jofer86 approved these changes
## Great Job Team!! :clap: :clap: :clap:

I can see that you guys completed all the changes requested by the previous TSE. The game runs properly, and the avoidable Linter errors were taken care of, I'm aware some of them are still not passing the Stickler linter, but it's understandable due to the nature of this project.

## Go Ahead and Merge! It's a :+1:

2019-08-13 15:02 UTC, merged