Request code review for Player class tests
KaushikShivam/tic-tac-toe pull request #5
Opened 2019-08-14 22:30 UTC by KaushikShivam

2019-08-14 22:31 UTC, KaushikShivam commented
We've tried to fix all the stickler errors. Only 4 are not passing and all of them relate to our blocks being too long. We can't fix it as we are being comprehensive about our tests and the specs/examples should only stay inside the describe/example group. Looking forward to your feedback.

2019-08-15 03:45 UTC, bellom requested changes
Hi Team, 
Great job using `Git Flow`, It was a nice test you wrote, i check if specs are failing if i break some code in tested method, yes it did fail, awesome !.
**Just two things left to do;**
1. include empty space around `it` block. 
2. fix linter (checkout this [link](https://github.com/microverseinc/linters-config#troubleshooting) for help.)
Kindly message me on slack if you still need help;
_Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you_

2019-08-15 03:45 UTC, bellom commented on spec/game_spec.rb
> +    it 'should return true if the slots match vertically from second column' do
Always Leave one empty line between feature, context or describe blocks. Do not leave empty line after the last such block in a group. [checkout this article to fix the issue](https://github.com/rubocop-hq/rspec-style-guide#empty-lines-between-describes)
kindly apply to the rest of the `it` block without space.

2019-08-15 03:45 UTC, bellom commented on spec/game_spec.rb
> +    it 'should return true if the slots match vertically from third column' do
**Another one !**
Leave one empty line between feature, context or describe blocks. Do not leave empty line after the last such block in a group. [checkout this article to fix the issue](https://github.com/rubocop-hq/rspec-style-guide#empty-lines-between-describes)

2019-08-15 15:11 UTC, KaushikShivam commented on spec/game_spec.rb
> +    it 'should return true if the slots match vertically from second column' do
We've fixed the suggested changes.

2019-08-15 15:11 UTC, KaushikShivam commented on spec/game_spec.rb
> +    it 'should return true if the slots match vertically from third column' do
Done

2019-08-15 17:43 UTC, bellom approved these changes
Hi Team, 
I can see your hard work on this project, don't forget to use `Git Flow` in the next project.
Go head and merge :+1:

2019-08-15 18:00 UTC, merged